/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;

import My_Classes.Author;
import My_Classes.Func_Class;
import My_Classes.Genre;
import My_Classes.Book;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class BookListForm extends javax.swing.JFrame {

    /**
     * Creates new form BooksListForm
     */
    Book book = new Book();
    Func_Class func = new Func_Class();
    Genre genre = new Genre();
    Author author = new Author();
    public BookListForm() {
        initComponents();
        func.customTableHeader(jTable_Book,new Color(42,187,155) , 16);
        func.showImage(jLabel_Image.getWidth(), jLabel_Image.getHeight(), null, "/My_Image/blank-profile-picture-g38e2328bd_1280.png", jLabel_Image);
        
        showTableWithBooks("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Value = new javax.swing.JTextField();
        jButton_SearchId = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Book = new javax.swing.JTable();
        jLabel_Image = new javax.swing.JLabel();
        jLabel_ISBN = new javax.swing.JLabel();
        jLabel_Price = new javax.swing.JLabel();
        jLabel_BookName = new javax.swing.JLabel();
        jLabel_PublisherName = new javax.swing.JLabel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel_GenreName = new javax.swing.JLabel();
        jLabel_AuthorName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_SearchByDate = new javax.swing.JButton();
        jDateChooser_From = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser_To = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_FormTitle.setBackground(new java.awt.Color(1, 152, 117));
        jLabel_FormTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("Books List");
        jLabel_FormTitle.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Value to search:");

        jTextField_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ValueActionPerformed(evt);
            }
        });

        jButton_SearchId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_SearchId.setText("Search");
        jButton_SearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchIdActionPerformed(evt);
            }
        });

        jTable_Book.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Book);

        jLabel_Image.setBackground(new java.awt.Color(255, 255, 102));
        jLabel_Image.setOpaque(true);

        jLabel_ISBN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_ISBN.setText("ISBN");

        jLabel_Price.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Price.setText("Price");

        jLabel_BookName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_BookName.setText("Name");

        jLabel_PublisherName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_PublisherName.setText("Publisher");

        jLabel_CloseForm.setBackground(new java.awt.Color(1, 152, 117));
        jLabel_CloseForm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("X");
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jLabel_GenreName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_GenreName.setText("Genre");

        jLabel_AuthorName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_AuthorName.setText("Author");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Date Recieved from:");

        jButton_SearchByDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_SearchByDate.setText("Search");
        jButton_SearchByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchByDateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("to:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(jTextField_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_SearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(jDateChooser_To, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_SearchByDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_ISBN)
                                    .addComponent(jLabel_BookName)
                                    .addComponent(jLabel_Price)
                                    .addComponent(jLabel_PublisherName)
                                    .addComponent(jLabel_AuthorName)
                                    .addComponent(jLabel_GenreName)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_SearchId)
                        .addComponent(jLabel3)
                        .addComponent(jButton_SearchByDate))
                    .addComponent(jDateChooser_To, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel_ISBN)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel_BookName)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_AuthorName)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_GenreName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_PublisherName)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Price)))
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jTextField_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ValueActionPerformed

    }//GEN-LAST:event_jTextField_ValueActionPerformed
    
    //show table of book
    public void showTableWithBooks(String query){
        ArrayList<Book> bookList  = book.bookList(query);
        
        //column names
        String[] colNames = {"ID","ISBN","NAME","AUTHOR_ID","GENRE_ID","QUANTITY","PUBLISHER","PRICE","DATE_RECEIVED"};
        
        //row name
        Object[][] rows = new Object[bookList .size()][colNames.length]; 
        
        
        for(int i=0; i < bookList.size();i++){
            rows[i][0]=bookList .get(i).getId();
            rows[i][1]=bookList .get(i).getIbsn();
            rows[i][2]=bookList .get(i).getName();
            rows[i][3]=bookList .get(i).getAuthor_id();
            rows[i][4]=bookList .get(i).getGenre_id();
            rows[i][5]=bookList .get(i).getQuantity();
            rows[i][6]=bookList .get(i).getPublisher();
            rows[i][7]=bookList .get(i).getPrice();
            rows[i][8]=bookList .get(i).getDate_received();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,colNames);
        jTable_Book.setModel(model);
        
    }
    
    private void jButton_SearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchIdActionPerformed
        //search and display data on the jtable
        String value = jTextField_Value.getText();
        String query = "SELECT * FROM `books` WHERE `name` LIKE '"+ value +"' or `description` LIKE '"+ value +"' or `publisher` LIKE '"+ value +"'";
        showTableWithBooks(query);
    }//GEN-LAST:event_jButton_SearchIdActionPerformed

    private void jTable_BookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BookMouseClicked
        
        Book selectBookId;
        try {
            //search id and show data
            Integer rowIndex = jTable_Book.getSelectedRow();
            Integer id = Integer.parseInt(jTable_Book.getModel().getValueAt(rowIndex, 0).toString());
            String isbn = (String) jTable_Book.getModel().getValueAt(rowIndex, 1);
            
            //select book id
            selectBookId = book.getBookObject(id, isbn);
            if(selectBookId != null){
                jLabel_ISBN.setText(selectBookId.getIbsn());
                jLabel_BookName.setText(selectBookId.getName());
                
                jLabel_AuthorName.setText(author.getAuthorById(selectBookId.getAuthor_id()).getFirstName()
                                        + " "+author.getAuthorById(selectBookId.getAuthor_id()).getLastName());
                
                jLabel_GenreName.setText(genre.getGenreById(selectBookId.getGenre_id()).getName());
                
                jLabel_PublisherName.setText(selectBookId.getPublisher());
                jLabel_Price.setText(String.valueOf(selectBookId.getPrice()));

                byte[] image = selectBookId.getCover();

                func.showImage(jLabel_Image.getWidth(), jLabel_Image.getHeight(),image ,"", jLabel_Image);
            }
            else {
                JOptionPane.showMessageDialog(null, "There is not existed the id: "+id, "Invalid", 3);
            }
        } catch (NumberFormatException ex) {
            //Logger.getLogger(EditBookForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Enter a valid Book id", "Invalid", 3);
        }
    }//GEN-LAST:event_jTable_BookMouseClicked

    private void jButton_SearchByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchByDateActionPerformed
        try{
            //search and display data on the jtable
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dateForm = dateFormat.format(jDateChooser_From.getDate());
            String dateTo = dateFormat.format(jDateChooser_To.getDate());
            String query = "SELECT * FROM `books` WHERE date_received BETWEEN '"+dateForm+"' and '"+dateTo+"'";
            showTableWithBooks(query);
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, "Select Two Date Before Clicking Search Button","No Dates Selected",2);
        }
        
    }//GEN-LAST:event_jButton_SearchByDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SearchByDate;
    private javax.swing.JButton jButton_SearchId;
    private com.toedter.calendar.JDateChooser jDateChooser_From;
    private com.toedter.calendar.JDateChooser jDateChooser_To;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_AuthorName;
    private javax.swing.JLabel jLabel_BookName;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JLabel jLabel_GenreName;
    private javax.swing.JLabel jLabel_ISBN;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Price;
    private javax.swing.JLabel jLabel_PublisherName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Book;
    private javax.swing.JTextField jTextField_Value;
    // End of variables declaration//GEN-END:variables

    
}
