/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;

import My_Classes.Book;
import My_Classes.Func_Class;
import My_Classes.Genre;
import My_Classes.Issue_Book;
import My_Classes.Member;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HOME
 */
public class ReturnBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    Member member = new Member();
    Func_Class func = new Func_Class();
    Genre genre = new Genre();
    
    String imagePath = "";
    Book book = new Book();
    Issue_Book issue = new Issue_Book();
    
    boolean existBook = false;
    boolean existMember = false;
    
    public ReturnBookForm() {
        initComponents();
        
        
       jSpinner_BookId.setEnabled(false);
       jSpinner_MemberId.setEnabled(false);
       showTableWithIssuedBooks("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();
        jButton_SearchBook = new javax.swing.JButton();
        jButton_ReturnBook = new javax.swing.JButton();
        jLabel_BookName = new javax.swing.JLabel();
        jButton_SearchMember = new javax.swing.JButton();
        jLabel_MemberName = new javax.swing.JLabel();
        jDateChooser_IssueDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel_CheckAvailabilityBook = new javax.swing.JLabel();
        jSpinner_BookId = new javax.swing.JSpinner();
        jSpinner_MemberId = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();
        jLabel_CloseForm = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ReturnBook = new javax.swing.JTable();
        jButton_LostBook = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_BookStatus = new javax.swing.JComboBox<>();
        jButton_Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_FormTitle.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_FormTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("Return Book");
        jLabel_FormTitle.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Enter book id:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Enter member id:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Return Date");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("Is this book available: ");

        jButton_SearchBook.setText("Search Book");
        jButton_SearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchBookActionPerformed(evt);
            }
        });

        jButton_ReturnBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_ReturnBook.setText("Return");
        jButton_ReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReturnBookActionPerformed(evt);
            }
        });

        jLabel_BookName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_BookName.setForeground(new java.awt.Color(0, 255, 255));
        jLabel_BookName.setText("Book name");
        jLabel_BookName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_BookNameMouseMoved(evt);
            }
        });
        jLabel_BookName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BookNameMouseClicked(evt);
            }
        });

        jButton_SearchMember.setText("Search Member");
        jButton_SearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchMemberActionPerformed(evt);
            }
        });

        jLabel_MemberName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_MemberName.setForeground(new java.awt.Color(0, 255, 255));
        jLabel_MemberName.setText("Member Full-name");
        jLabel_MemberName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseMoved(evt);
            }
        });
        jLabel_MemberName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MemberNameMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Issue Date");

        jLabel_CheckAvailabilityBook.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CheckAvailabilityBook.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_CheckAvailabilityBook.setForeground(new java.awt.Color(0, 255, 255));
        jLabel_CheckAvailabilityBook.setText("Yes - No");
        jLabel_CheckAvailabilityBook.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_CheckAvailabilityBookMouseMoved(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("Note:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        jLabel_CloseForm.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CloseForm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("X");
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jTable_ReturnBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_ReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ReturnBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_ReturnBook);

        jButton_LostBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_LostBook.setText("Lost");
        jButton_LostBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LostBookActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Select Book's status:");

        jComboBox_BookStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Issued", "Returned", "Lost" }));
        jComboBox_BookStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_BookStatusActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jButton_ReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_MemberName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinner_MemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton_SearchMember, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton_LostBook, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel_BookName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner_BookId, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton_SearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_CheckAvailabilityBook))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_BookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton_SearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_BookId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_BookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_BookName)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_SearchMember, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jSpinner_MemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))))
                        .addComponent(jLabel_MemberName)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel_CheckAvailabilityBook))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_LostBook, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_ReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jLabel_MemberNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MemberNameMouseMoved

    private void jButton_SearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchMemberActionPerformed
        
        int memberId = (int)jSpinner_MemberId.getValue();
        try {
            Member selectedMember = member.showOneMember(memberId);
            if(selectedMember != null){
                jLabel_MemberName.setText(selectedMember.getFirstName() +" "+ selectedMember.getLastName());
                
            }
            else{
                JOptionPane.showMessageDialog(null, "this member doesn't exist", "Member not Found",2);
                jLabel_MemberName.setText("Member Full-name");
                existMember = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_SearchMemberActionPerformed

    private void jLabel_BookNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookNameMouseMoved
        
    }//GEN-LAST:event_jLabel_BookNameMouseMoved

    private void jButton_ReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReturnBookActionPerformed
        try {
            int bookId = (int)jSpinner_BookId.getValue();
            int memberId = (int)jSpinner_MemberId.getValue();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String issueDate = dateFormat.format(jDateChooser_IssueDate.getDate()); 
            String returnDate = dateFormat.format(jDateChooser_ReturnDate.getDate()); 
            String note = jTextArea_Note.getText();

            Date issDate = dateFormat.parse(issueDate);
            Date retDate = dateFormat.parse(returnDate);
            
            if(retDate.before(issDate)){
                JOptionPane.showMessageDialog(null, "The return date must be after issue date", "Wrong Return Date",2);
            }
            else{
                issue.updateIssue(bookId, memberId, "returned", issueDate, returnDate, note);
                jSpinner_BookId.setValue(0);
                jSpinner_MemberId.setValue(0);
                jLabel_BookName.setText("Book name");
                jLabel_MemberName.setText("Member Full-name");
                jLabel_CheckAvailabilityBook.setText("Yes - No");
                jLabel_CheckAvailabilityBook.setForeground(new Color(0,255,255));
                jDateChooser_IssueDate.setDate(new Date());
                jDateChooser_ReturnDate.setDate(new Date());
                jTextArea_Note.setText("");
            }
        
        } catch (ParseException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Select issued book to update", "Update status error",2);
        }
    }//GEN-LAST:event_jButton_ReturnBookActionPerformed

    private void jButton_SearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchBookActionPerformed
        
        int bookId = (int)jSpinner_BookId.getValue();
        try {
            
            Book selectedBook = book.showOneBook(bookId);
            
            if(selectedBook != null){
                jLabel_BookName.setText(selectedBook.getName());
                jLabel_CheckAvailabilityBook.setText("Yes");
            }
            else{
                JOptionPane.showMessageDialog(null, "this book doesn't exist", "Book not Found",2);
                jLabel_CheckAvailabilityBook.setText("Yes - No");
                jLabel_BookName.setText("Book Name");
                existBook = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_SearchBookActionPerformed

    private void jLabel_CheckAvailabilityBookMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CheckAvailabilityBookMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_CheckAvailabilityBookMouseMoved

    private void jLabel_BookNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookNameMouseClicked
        int book_id = (int)jSpinner_BookId.getValue();
        BookInfoCardForm bookinfoC = new BookInfoCardForm(book_id);
        bookinfoC.setVisible(true);
    }//GEN-LAST:event_jLabel_BookNameMouseClicked

    private void jLabel_MemberNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberNameMouseClicked
        // TODO add your handling code here:
        int member_id = (int)jSpinner_MemberId.getValue();
        MemberInfoCardForm memberinfoC = new MemberInfoCardForm(member_id);
        memberinfoC.setVisible(true);
    }//GEN-LAST:event_jLabel_MemberNameMouseClicked

    private void jTable_ReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ReturnBookMouseClicked
        int index = jTable_ReturnBook.getSelectedRow();
        int book_id =(int) jTable_ReturnBook.getValueAt(index, 0);
        
        int member_id = (int)jTable_ReturnBook.getValueAt(index, 1);
        
        String status = jTable_ReturnBook.getValueAt(index, 2).toString();
        String note = jTable_ReturnBook.getValueAt(index, 5).toString();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
        try {
            Book selectedBook = book.showOneBook(book_id);
            Member selectedMember = member.showOneMember(member_id);
            jSpinner_BookId.setValue(book_id);
            jLabel_BookName.setText(selectedBook.getName());
            jSpinner_MemberId.setValue(member_id);
            jLabel_MemberName.setText(selectedMember.getFirstName() +" " +selectedMember.getLastName());
            Date issDate = new SimpleDateFormat("yyyy-mm-dd").parse(jTable_ReturnBook.getValueAt(index, 3).toString());
            jDateChooser_IssueDate.setDate(issDate);
            Date retDate = new SimpleDateFormat("yyyy-mm-dd").parse(jTable_ReturnBook.getValueAt(index, 4).toString());
            jDateChooser_ReturnDate.setDate(retDate);
            jTextArea_Note.setText(note);
        } catch (ParseException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jTable_ReturnBookMouseClicked

    private void jButton_LostBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LostBookActionPerformed

        int bookId = (int)jSpinner_BookId.getValue();
        int memberId = (int)jSpinner_MemberId.getValue();
        String note = jTextArea_Note.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
                String issueDate = dateFormat.format(jDateChooser_IssueDate.getDate()); 
                String returnDate = dateFormat.format(jDateChooser_ReturnDate.getDate()); 
                issue.updateIssue(bookId, memberId, "lost", issueDate, returnDate, note);
                int quantity = book.showOneBook(bookId).getQuantity();
                book.setQuantityMinusOne(bookId,quantity-1);
                
                jSpinner_BookId.setValue(0);
                jSpinner_MemberId.setValue(0);
                jLabel_BookName.setText("Book name");
                jLabel_MemberName.setText("Member Full-name");
                jLabel_CheckAvailabilityBook.setText("Yes - No");
                jLabel_CheckAvailabilityBook.setForeground(new Color(0,255,255));
                jTextArea_Note.setText("");
        
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Select issued book to update", "Update status error",2);
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_LostBookActionPerformed

    private void jComboBox_BookStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_BookStatusActionPerformed
        String status = jComboBox_BookStatus.getSelectedItem().toString();
        if(status.equals("All")){
            showTableWithIssuedBooks(status);
        }
        showTableWithIssuedBooks(status);
    }//GEN-LAST:event_jComboBox_BookStatusActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        int book_Id;
        int member_Id;
        try{
        String status = jComboBox_BookStatus.getSelectedItem().toString();
        
        int index = jTable_ReturnBook.getSelectedRow();
        int bookId = Integer.parseInt(jTable_ReturnBook.getValueAt(index, 0).toString());
        int memberId = Integer.parseInt(jTable_ReturnBook.getValueAt(index, 1).toString());
        String issueDate = jTable_ReturnBook.getValueAt(index, 3).toString();
        
            issue.removeFromIssueTable(bookId, memberId, issueDate);
            showTableWithIssuedBooks(status);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Select the issue one to delete" , "Delete Error",2);
        }
        
    }//GEN-LAST:event_jButton_DeleteActionPerformed
       
    //show table
    public void showTableWithIssuedBooks(String status){
        ArrayList<Issue_Book> isList  = issue.issuebookList(status);
        
        //column names
        String[] colNames = {"Book Id","Member Id","Status","Issued Date","Return Date","Note"};
        
        //row name
        Object[][] rows = new Object[isList .size()][colNames.length]; 
        
        
        for(int i=0; i < isList.size();i++){
            rows[i][0]=isList .get(i).getBook_id();
            rows[i][1]=isList .get(i).getMember_id();
            rows[i][2]=isList .get(i).getStatus();
            rows[i][3]=isList .get(i).getIssue_date();
            rows[i][4]=isList .get(i).getReturn_date();
            rows[i][5]=isList .get(i).getNote();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,colNames);
        jTable_ReturnBook.setModel(model);
                
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_LostBook;
    private javax.swing.JButton jButton_ReturnBook;
    private javax.swing.JButton jButton_SearchBook;
    private javax.swing.JButton jButton_SearchMember;
    private javax.swing.JComboBox<String> jComboBox_BookStatus;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_BookName;
    private javax.swing.JLabel jLabel_CheckAvailabilityBook;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JLabel jLabel_MemberName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_BookId;
    private javax.swing.JSpinner jSpinner_MemberId;
    private javax.swing.JTable jTable_ReturnBook;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
